### ISSUE TITLE
Charity Hyperlink

### ISSUE THREAD

**Issue by smartin160** [matt1018/RBOColorWalk#29]
would it be possible to place a hyperlink in the Charity title?
for instance <hyper>Treehouse<\hyper> - Serving Youth in Foster Care

**Comment by matt1018** [comment]
So the solution I was thinking of for this was to allow you to put html into the title of the charity so you could add an anchor tag (<a href=…) and it would actually show up as a link (be default it is escaped which means you will see the <a href in the title of the event). The problem with this is that I use that charity name all over the place: on the home page, on the event page, in the facebook share text, in the transaction reporting. While most of these uses would render alright with a link in the middle of them, not all of them would.  In fact the facebook sharing text would probably break facebook sharing.
1. One solution would be to just add a link in the description of the event...currently that would be escaped as well, but I could fix that easy enough. 
2. Another solution would be to create a second field that is used in the couple places where this would really make sense, but not everywhere else.
Actually, now that I think about it, I like option 2. I'll go ahead and implement that. Might be a little confusing for admins, but there are only a few of us who would be confused. :-)

**Comment by smartin160** [comment]
from what I have seen, I like that solution :)

Steve Martin
(425) 293-3185
(360) 453-7342
