### ISSUE TITLE
Create Event Admins

### ISSUE THREAD

**Issue by matt1018** [matt1018/RBOColorWalk#3]
Support Event Admins.
* can edit fields
* can see admin details page
* can optionally get emails when someone registers (or donates?)

**Comment by matt1018** [comment]
Perhaps Jurisdiction Admins instead?

**Comment by smartin160** [comment]
Jurisdiction admins would be nice.  You and I as site admins, and then admins for say California or Nevada?  We can see and modify all, they can see and modify theirs, but not the others?  Makes sense.  But not necessary until we actually have other jurisdictions :)

**Comment by matt1018** [comment]
Okay, this is setup now. To make a user a Jurisdiction Admin, go to Admin -> Jurisdictions -> specific jurisdiction -> Create New Admin. They have to already be a user on the platform.

Sent email to Kris Arnold asking her to create a user account so we can set her up as a jurisdiction admin.
