### ISSUE TITLE
Add Greek Letters

### ISSUE THREAD

**Issue by smartin160** [matt1018/RBOColorWalk#30]
Now that it is official, add the Greek letters to the colorwalk page?  Maybe 
<Greek>RBO<\Greek>
RBO Color Walk

**Comment by matt1018** [comment]
Started looking into this. The font I used for the titles on the pages doesn't support greek letters, so I'll need to find another font.  Working on it...

**Comment by matt1018** [comment]
Okay...found a fun font that supported greek letters and it is now being used on the site. Changed the event name to include the greek letters. Need some guidance around what to do about the name in the header (to the left of the menu). We can change it easily enough, but then it doesn't match the URL. Also, if we are really reaching out to other jurisdictions (who haven't bought into the greek letter thing), do we really want to change the site name?  I believe you can put greek letters in URLs, but nobody will know how to type them into their browsers. 

Finally, I've looked through a bunch of pages and have found a few places where the font change has screwed up the spacing on the page. If you come across anyplace I missed, let me know.

**Comment by smartin160** [comment]
I think we leave the URL and the title page as is, Greek letters in the event.  Or even a png of the greek letters?  Not sure....  Like this?  Your thoughts? 
       "GGG" 
RBO Color Walk

**Comment by matt1018** [comment]
I like leaving the URL and title page as is. I already adjusted the name of the event to have greek letters. We're you saying 

1. "PBΩ RBO Color Walk" or
2. "PBΩ Color Walk"?


This can be done by just changing the name of the event in the admin interface.

**Comment by matt1018** [comment]
I think this one is resolved.
