### ISSUE TITLE
Donation Page Link on "My Events" page

### ISSUE THREAD

**Issue by smartin160** [matt1018/RBOColorWalk#35]
Add links for the "My donation Pages" on the main "My Events" page for users.  Many people can not find the donation page on the menu because they are not looking for it.  People see the "SHARE" on facebook and twitter and then wonder why people can't donate to them with that link.  For 2019, no need to fix for 2018

**Comment by matt1018** [comment]
Under the "Registered" we now list each person registered and have links to their donation pages.
