### ISSUE TITLE
Donation Only Button on Main Page

### ISSUE THREAD

**Issue by matt1018** [matt1018/RBOColorWalk#4]

**Comment by matt1018** [comment]
Maybe a dropdown of a participant to give credit to?

Or something separate...I don't know

**Comment by smartin160** [comment]
somehow give credit to a registered participant.  I know that was something that they liked but it didn't quite work right.  For instance your brother could donate in the name of Sophie, and she gets credit for it.

**Comment by matt1018** [comment]
done
